project:
  type: book

book:
  title: "The {traits.build} standard, R package and workflow manual"
  author: ["Elizabeth Wenk", "Daniel Falster", "Sophie Yang"]
  page-footer: "How to get help: <https://traitecoevo.github.io/traits.build-book/help.html><br>Copyright 2023, Daniel Falster and Elizabeth Wenk" 

  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - motivation.qmd
        - workflow.qmd
        - usage_examples.qmd
        - austraits_experience.qmd
    - part: About the traits.build data standard 
      chapters:
        - database_structure.qmd
    - part: Using `traits.build` to build a compliation
      chapters:
        - traits_build.qmd
        - compilation_file_structure.qmd
        - adding_data.qmd
        - dictionary.qmd
    - part: Using the outputs from `traits.build`
      chapters:
        - using_data.qmd
    - part: Tutorials
      chapters:
        - tutorials.qmd
        - tutorial_compilation.qmd
        - tutorial_dataset_1.qmd
        - tutorial_dataset_2.qmd
        - tutorial_dataset_3.qmd
        - tutorial_dataset_4.qmd
    - part: Troubleshooting
      chapters:
        - help.qmd
        - troubleshooting.qmd
        - debugging.qmd

  appendices:
    - yaml.qmd
  
format:
  html:
    theme: cosmo
