project:
  type: book

book:
  title: "The {traits.build} standard, R package and workflow manual"
  author: ["Elizabeth Wenk", "Daniel Falster", "Sophie Yang"]
  page-footer: "How to get help: <https://traitecoevo.github.io/traits.build-book/help.html><br>Copyright 2023, Daniel Falster and Elizabeth Wenk" 
  page-navigation: true
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - motivation.qmd
        - workflow.qmd
        - usage_examples.qmd
    - part: Data structure and standard 
      chapters:
        - database_structure.qmd
    - part: Using `traits.build`
      chapters:
        - traits_build.qmd
        - file_structure.qmd
        - dictionary.qmd
        - adding_data.qmd
        - custom_R_code.qmd
    - part: Using the outputs
      chapters:
        - using_data.qmd
    - part: Tutorials
      chapters:
        - tutorials.qmd
        - tutorial_compilation.qmd
        - tutorial_dataset_1.qmd
        - tutorial_dataset_2.qmd
        - tutorial_dataset_3.qmd
        - tutorial_dataset_4.qmd
    - part: Troubleshooting
      chapters:
        - help.qmd
        - troubleshooting.qmd
        - debugging.qmd

  appendices:
    - csv.qmd
    - yaml.qmd
  
format:
  html:
    theme: cosmo
    number-depth: 2
